import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'FiscalProfileOperationCreate', value: 'fiscalProfileOperationCreate' },
    { name: 'FiscalProfileOperationDelete', value: 'fiscalProfileOperationDelete' },
    { name: 'FiscalProfileOperationOpReadByCode', value: 'fiscalProfileOperationOpReadByCode' },
    { name: 'FiscalProfileOperationRead', value: 'fiscalProfileOperationRead' },
    { name: 'FiscalProfileOperationReadById', value: 'fiscalProfileOperationReadById' },
    { name: 'FiscalProfileOperationUpdate', value: 'fiscalProfileOperationUpdate' },
    { name: 'FiscalProfilePersonCreate', value: 'fiscalProfilePersonCreate' },
    { name: 'FiscalProfilePersonDelete', value: 'fiscalProfilePersonDelete' },
    { name: 'FiscalProfilePersonRead', value: 'fiscalProfilePersonRead' },
    { name: 'FiscalProfilePersonReadById', value: 'fiscalProfilePersonReadById' },
    { name: 'FiscalProfilePersonUpdate', value: 'fiscalProfilePersonUpdate' },
    { name: 'FiscalProfileProductCreate', value: 'fiscalProfileProductCreate' },
    { name: 'FiscalProfileProductDelete', value: 'fiscalProfileProductDelete' },
    { name: 'FiscalProfileProductRead', value: 'fiscalProfileProductRead' },
    { name: 'FiscalProfileProductReadById', value: 'fiscalProfileProductReadById' },
    { name: 'FiscalProfileProductUpdate', value: 'fiscalProfileProductUpdate' },
    { name: 'FiscalRegionCreate', value: 'fiscalRegionCreate' },
    { name: 'FiscalRegionDelete', value: 'fiscalRegionDelete' },
    { name: 'FiscalRegionOpReadByCode', value: 'fiscalRegionOpReadByCode' },
    { name: 'FiscalRegionRead', value: 'fiscalRegionRead' },
    { name: 'FiscalRegionReadById', value: 'fiscalRegionReadById' },
    { name: 'FiscalRegionUpdate', value: 'fiscalRegionUpdate' },
    { name: 'FiscalYearCreate', value: 'fiscalYearCreate' },
    { name: 'FiscalYearDelete', value: 'fiscalYearDelete' },
    { name: 'FiscalYearOpPartialClosure', value: 'fiscalYearOpPartialClosure' },
    { name: 'FiscalYearOpPartialClosureRevert', value: 'fiscalYearOpPartialClosureRevert' },
    { name: 'FiscalYearOpPublish', value: 'fiscalYearOpPublish' },
    { name: 'FiscalYearOpPublishRevert', value: 'fiscalYearOpPublishRevert' },
    { name: 'FiscalYearOpRead', value: 'fiscalYearOpRead' },
    { name: 'FiscalYearRead', value: 'fiscalYearRead' },
    { name: 'FiscalYearReadById', value: 'fiscalYearReadById' },
    { name: 'FiscalYearUpdate', value: 'fiscalYearUpdate' },
    { name: 'IncomingInvoiceCreate', value: 'incomingInvoiceCreate' },
    { name: 'IncomingInvoiceDelete', value: 'incomingInvoiceDelete' },
    { name: 'IncomingInvoiceItemCreate', value: 'incomingInvoiceItemCreate' },
    { name: 'IncomingInvoiceItemDelete', value: 'incomingInvoiceItemDelete' },
    { name: 'IncomingInvoiceItemRead', value: 'incomingInvoiceItemRead' },
    { name: 'IncomingInvoiceItemReadById', value: 'incomingInvoiceItemReadById' },
    { name: 'IncomingInvoiceItemUpdate', value: 'incomingInvoiceItemUpdate' },
    { name: 'IncomingInvoiceOpApprove', value: 'incomingInvoiceOpApprove' },
    { name: 'IncomingInvoiceOpApproveDivergences', value: 'incomingInvoiceOpApproveDivergences' },
    { name: 'IncomingInvoiceOpApproveRevert', value: 'incomingInvoiceOpApproveRevert' },
    { name: 'IncomingInvoiceOpCreate', value: 'incomingInvoiceOpCreate' },
    { name: 'IncomingInvoiceOpCreateFromIncomingList', value: 'incomingInvoiceOpCreateFromIncomingList' },
    { name: 'IncomingInvoiceOpPrepare', value: 'incomingInvoiceOpPrepare' },
    { name: 'IncomingInvoiceOpPrepareRevert', value: 'incomingInvoiceOpPrepareRevert' },
    { name: 'IncomingInvoiceOpReject', value: 'incomingInvoiceOpReject' },
    { name: 'IncomingInvoiceOpRejectRevert', value: 'incomingInvoiceOpRejectRevert' },
    { name: 'IncomingInvoiceOpReturn', value: 'incomingInvoiceOpReturn' },
    { name: 'IncomingInvoiceOpTaxationCalc', value: 'incomingInvoiceOpTaxationCalc' },
    { name: 'IncomingInvoiceOpUpdatePrepared', value: 'incomingInvoiceOpUpdatePrepared' },
    { name: 'IncomingInvoicePaymentCreate', value: 'incomingInvoicePaymentCreate' },
    { name: 'IncomingInvoicePaymentDelete', value: 'incomingInvoicePaymentDelete' },
    { name: 'IncomingInvoicePaymentRead', value: 'incomingInvoicePaymentRead' },
    { name: 'IncomingInvoicePaymentReadById', value: 'incomingInvoicePaymentReadById' },
    { name: 'IncomingInvoicePaymentUpdate', value: 'incomingInvoicePaymentUpdate' },
    { name: 'IncomingInvoiceRead', value: 'incomingInvoiceRead' },
    { name: 'IncomingInvoiceReadById', value: 'incomingInvoiceReadById' },
    { name: 'IncomingInvoiceUpdate', value: 'incomingInvoiceUpdate' },
    { name: 'InvoiceItemAccountingCreate', value: 'invoiceItemAccountingCreate' },
    { name: 'InvoiceItemAccountingDelete', value: 'invoiceItemAccountingDelete' },
    { name: 'InvoiceItemAccountingRead', value: 'invoiceItemAccountingRead' },
    { name: 'InvoiceItemAccountingReadById', value: 'invoiceItemAccountingReadById' },
    { name: 'InvoiceItemAccountingUpdate', value: 'invoiceItemAccountingUpdate' },
    { name: 'InvoiceReferenceCreate', value: 'invoiceReferenceCreate' },
    { name: 'InvoiceReferenceDelete', value: 'invoiceReferenceDelete' },
    { name: 'InvoiceReferenceRead', value: 'invoiceReferenceRead' },
    { name: 'InvoiceReferenceReadById', value: 'invoiceReferenceReadById' },
    { name: 'InvoiceReferenceUpdate', value: 'invoiceReferenceUpdate' },
    { name: 'InvoiceSeriesCreate', value: 'invoiceSeriesCreate' },
    { name: 'InvoiceSeriesDelete', value: 'invoiceSeriesDelete' },
    { name: 'InvoiceSeriesOpGetNextNumber', value: 'invoiceSeriesOpGetNextNumber' },
    { name: 'InvoiceSeriesOpUpdateLastNumber', value: 'invoiceSeriesOpUpdateLastNumber' },
    { name: 'InvoiceSeriesRead', value: 'invoiceSeriesRead' },
    { name: 'InvoiceSeriesReadById', value: 'invoiceSeriesReadById' },
    { name: 'InvoiceSeriesUpdate', value: 'invoiceSeriesUpdate' },
    { name: 'OutgoingInvoiceCreate', value: 'outgoingInvoiceCreate' },
    { name: 'OutgoingInvoiceDelete', value: 'outgoingInvoiceDelete' },
    { name: 'OutgoingInvoiceItemCreate', value: 'outgoingInvoiceItemCreate' },
    { name: 'OutgoingInvoiceItemDelete', value: 'outgoingInvoiceItemDelete' },
    { name: 'OutgoingInvoiceItemRead', value: 'outgoingInvoiceItemRead' },
    { name: 'OutgoingInvoiceItemReadById', value: 'outgoingInvoiceItemReadById' },
    { name: 'OutgoingInvoiceItemUpdate', value: 'outgoingInvoiceItemUpdate' },
    { name: 'OutgoingInvoiceOpApprove', value: 'outgoingInvoiceOpApprove' },
    { name: 'OutgoingInvoiceOpApproveRevert', value: 'outgoingInvoiceOpApproveRevert' },
    { name: 'OutgoingInvoiceOpCancel', value: 'outgoingInvoiceOpCancel' },
    { name: 'OutgoingInvoiceOpCreate', value: 'outgoingInvoiceOpCreate' },
    { name: 'OutgoingInvoiceOpDiscount', value: 'outgoingInvoiceOpDiscount' },
    { name: 'OutgoingInvoiceOpOutgoingListBind', value: 'outgoingInvoiceOpOutgoingListBind' },
    { name: 'OutgoingInvoiceOpPrepare', value: 'outgoingInvoiceOpPrepare' },
    { name: 'OutgoingInvoiceOpPrepareRevert', value: 'outgoingInvoiceOpPrepareRevert' },
    { name: 'OutgoingInvoiceOpReturn', value: 'outgoingInvoiceOpReturn' },
    { name: 'OutgoingInvoiceOpTaxationCalc', value: 'outgoingInvoiceOpTaxationCalc' },
    { name: 'OutgoingInvoiceOpUpdatePrepared', value: 'outgoingInvoiceOpUpdatePrepared' },
    { name: 'OutgoingInvoicePaymentCreate', value: 'outgoingInvoicePaymentCreate' },
    { name: 'OutgoingInvoicePaymentDelete', value: 'outgoingInvoicePaymentDelete' },
    { name: 'OutgoingInvoicePaymentRead', value: 'outgoingInvoicePaymentRead' },
    { name: 'OutgoingInvoicePaymentReadById', value: 'outgoingInvoicePaymentReadById' },
    { name: 'OutgoingInvoicePaymentUpdate', value: 'outgoingInvoicePaymentUpdate' },
    { name: 'OutgoingInvoiceRead', value: 'outgoingInvoiceRead' },
    { name: 'OutgoingInvoiceReadById', value: 'outgoingInvoiceReadById' },
    { name: 'OutgoingInvoiceUpdate', value: 'outgoingInvoiceUpdate' }
  ],
  default: 'fiscalProfileOperationCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
