import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'BomCreate', value: 'bomCreate' },
    { name: 'BomDelete', value: 'bomDelete' },
    { name: 'BomItemCreate', value: 'bomItemCreate' },
    { name: 'BomItemDelete', value: 'bomItemDelete' },
    { name: 'BomItemRead', value: 'bomItemRead' },
    { name: 'BomItemReadById', value: 'bomItemReadById' },
    { name: 'BomItemUpdate', value: 'bomItemUpdate' },
    { name: 'BomOpClone', value: 'bomOpClone' },
    { name: 'BomRead', value: 'bomRead' },
    { name: 'BomReadById', value: 'bomReadById' },
    { name: 'BomUpdate', value: 'bomUpdate' },
    { name: 'OperationCreate', value: 'operationCreate' },
    { name: 'OperationDelete', value: 'operationDelete' },
    { name: 'OperationRead', value: 'operationRead' },
    { name: 'OperationReadById', value: 'operationReadById' },
    { name: 'OperationTypeAccountCreate', value: 'operationTypeAccountCreate' },
    { name: 'OperationTypeAccountDelete', value: 'operationTypeAccountDelete' },
    { name: 'OperationTypeAccountRead', value: 'operationTypeAccountRead' },
    { name: 'OperationTypeAccountReadById', value: 'operationTypeAccountReadById' },
    { name: 'OperationTypeAccountUpdate', value: 'operationTypeAccountUpdate' },
    { name: 'OperationTypeCreate', value: 'operationTypeCreate' },
    { name: 'OperationTypeDelete', value: 'operationTypeDelete' },
    { name: 'OperationTypeRead', value: 'operationTypeRead' },
    { name: 'OperationTypeReadById', value: 'operationTypeReadById' },
    { name: 'OperationTypeUpdate', value: 'operationTypeUpdate' },
    { name: 'OperationUpdate', value: 'operationUpdate' },
    { name: 'ProductionBatchCreate', value: 'productionBatchCreate' },
    { name: 'ProductionBatchDelete', value: 'productionBatchDelete' },
    { name: 'ProductionBatchOpApprove', value: 'productionBatchOpApprove' },
    { name: 'ProductionBatchOpApproveRevert', value: 'productionBatchOpApproveRevert' },
    { name: 'ProductionBatchOpPrepare', value: 'productionBatchOpPrepare' },
    { name: 'ProductionBatchOpPrepareRevert', value: 'productionBatchOpPrepareRevert' },
    { name: 'ProductionBatchRead', value: 'productionBatchRead' },
    { name: 'ProductionBatchReadById', value: 'productionBatchReadById' },
    { name: 'ProductionBatchUpdate', value: 'productionBatchUpdate' },
    { name: 'ProductionOrderCreate', value: 'productionOrderCreate' },
    { name: 'ProductionOrderDelete', value: 'productionOrderDelete' },
    { name: 'ProductionOrderOpApprove', value: 'productionOrderOpApprove' },
    { name: 'ProductionOrderOpApproveRevert', value: 'productionOrderOpApproveRevert' },
    { name: 'ProductionOrderOpCreate', value: 'productionOrderOpCreate' },
    { name: 'ProductionOrderOpFinish', value: 'productionOrderOpFinish' },
    { name: 'ProductionOrderOpFinishRevert', value: 'productionOrderOpFinishRevert' },
    { name: 'ProductionOrderOpPrepare', value: 'productionOrderOpPrepare' },
    { name: 'ProductionOrderOpPrepareRevert', value: 'productionOrderOpPrepareRevert' },
    { name: 'ProductionOrderRead', value: 'productionOrderRead' },
    { name: 'ProductionOrderReadById', value: 'productionOrderReadById' },
    { name: 'ProductionOrderUpdate', value: 'productionOrderUpdate' },
    { name: 'ProductionProfileCreate', value: 'productionProfileCreate' },
    { name: 'ProductionProfileDelete', value: 'productionProfileDelete' },
    { name: 'ProductionProfileRead', value: 'productionProfileRead' },
    { name: 'ProductionProfileReadById', value: 'productionProfileReadById' },
    { name: 'ProductionProfileUpdate', value: 'productionProfileUpdate' },
    { name: 'ProductionStepConsumptionCreate', value: 'productionStepConsumptionCreate' },
    { name: 'ProductionStepConsumptionDelete', value: 'productionStepConsumptionDelete' },
    { name: 'ProductionStepConsumptionOpCalculate', value: 'productionStepConsumptionOpCalculate' },
    { name: 'ProductionStepConsumptionRead', value: 'productionStepConsumptionRead' },
    { name: 'ProductionStepConsumptionReadById', value: 'productionStepConsumptionReadById' },
    { name: 'ProductionStepConsumptionUpdate', value: 'productionStepConsumptionUpdate' },
    { name: 'ProductionStepCreate', value: 'productionStepCreate' },
    { name: 'ProductionStepDelete', value: 'productionStepDelete' },
    { name: 'ProductionStepOpCreate', value: 'productionStepOpCreate' },
    { name: 'ProductionStepOpFinish', value: 'productionStepOpFinish' },
    { name: 'ProductionStepOpFinishRevert', value: 'productionStepOpFinishRevert' },
    { name: 'ProductionStepOpStart', value: 'productionStepOpStart' },
    { name: 'ProductionStepOpStartRevert', value: 'productionStepOpStartRevert' },
    { name: 'ProductionStepProductionCreate', value: 'productionStepProductionCreate' },
    { name: 'ProductionStepProductionDelete', value: 'productionStepProductionDelete' },
    { name: 'ProductionStepProductionRead', value: 'productionStepProductionRead' },
    { name: 'ProductionStepProductionReadById', value: 'productionStepProductionReadById' },
    { name: 'ProductionStepProductionUpdate', value: 'productionStepProductionUpdate' },
    { name: 'ProductionStepRead', value: 'productionStepRead' },
    { name: 'ProductionStepReadById', value: 'productionStepReadById' },
    { name: 'ProductionStepUpdate', value: 'productionStepUpdate' }
  ],
  default: 'bomCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
