import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'AddressCreate', value: 'addressCreate' },
    { name: 'AddressDelete', value: 'addressDelete' },
    { name: 'AddressProfileCreate', value: 'addressProfileCreate' },
    { name: 'AddressProfileDelete', value: 'addressProfileDelete' },
    { name: 'AddressProfileRead', value: 'addressProfileRead' },
    { name: 'AddressProfileReadById', value: 'addressProfileReadById' },
    { name: 'AddressProfileUpdate', value: 'addressProfileUpdate' },
    { name: 'AddressRead', value: 'addressRead' },
    { name: 'AddressReadById', value: 'addressReadById' },
    { name: 'AddressUpdate', value: 'addressUpdate' },
    { name: 'HandlingUnitCreate', value: 'handlingUnitCreate' },
    { name: 'HandlingUnitDelete', value: 'handlingUnitDelete' },
    { name: 'HandlingUnitRead', value: 'handlingUnitRead' },
    { name: 'HandlingUnitReadById', value: 'handlingUnitReadById' },
    { name: 'HandlingUnitUpdate', value: 'handlingUnitUpdate' },
    { name: 'IncomingListCreate', value: 'incomingListCreate' },
    { name: 'IncomingListDelete', value: 'incomingListDelete' },
    { name: 'IncomingListItemCreate', value: 'incomingListItemCreate' },
    { name: 'IncomingListItemDelete', value: 'incomingListItemDelete' },
    { name: 'IncomingListItemRead', value: 'incomingListItemRead' },
    { name: 'IncomingListItemReadById', value: 'incomingListItemReadById' },
    { name: 'IncomingListItemUpdate', value: 'incomingListItemUpdate' },
    { name: 'IncomingListOpImportFromOutgoingList', value: 'incomingListOpImportFromOutgoingList' },
    { name: 'IncomingListOpPrepare', value: 'incomingListOpPrepare' },
    { name: 'IncomingListOpPrepareRevert', value: 'incomingListOpPrepareRevert' },
    { name: 'IncomingListRead', value: 'incomingListRead' },
    { name: 'IncomingListReadById', value: 'incomingListReadById' },
    { name: 'IncomingListUpdate', value: 'incomingListUpdate' },
    { name: 'InventoryAdjustmentCreate', value: 'inventoryAdjustmentCreate' },
    { name: 'InventoryAdjustmentDelete', value: 'inventoryAdjustmentDelete' },
    { name: 'InventoryAdjustmentOpCreate', value: 'inventoryAdjustmentOpCreate' },
    { name: 'InventoryAdjustmentRead', value: 'inventoryAdjustmentRead' },
    { name: 'InventoryAdjustmentReadById', value: 'inventoryAdjustmentReadById' },
    { name: 'InventoryAdjustmentUpdate', value: 'inventoryAdjustmentUpdate' },
    { name: 'InventoryCheckCreate', value: 'inventoryCheckCreate' },
    { name: 'InventoryCheckDelete', value: 'inventoryCheckDelete' },
    { name: 'InventoryCheckRead', value: 'inventoryCheckRead' },
    { name: 'InventoryCheckReadById', value: 'inventoryCheckReadById' },
    { name: 'InventoryCheckUpdate', value: 'inventoryCheckUpdate' },
    { name: 'InventoryCreate', value: 'inventoryCreate' },
    { name: 'InventoryDelete', value: 'inventoryDelete' },
    { name: 'InventoryOpApprove', value: 'inventoryOpApprove' },
    { name: 'InventoryOpApproveRevert', value: 'inventoryOpApproveRevert' },
    { name: 'InventoryOpFinish', value: 'inventoryOpFinish' },
    { name: 'InventoryOpFinishRevert', value: 'inventoryOpFinishRevert' },
    { name: 'InventoryOpPrepare', value: 'inventoryOpPrepare' },
    { name: 'InventoryOpPrepareRevert', value: 'inventoryOpPrepareRevert' },
    { name: 'InventoryOpProcess', value: 'inventoryOpProcess' },
    { name: 'InventoryOpProcessRevert', value: 'inventoryOpProcessRevert' },
    { name: 'InventoryOpStart', value: 'inventoryOpStart' },
    { name: 'InventoryOpStartRevert', value: 'inventoryOpStartRevert' },
    { name: 'InventoryProfileCreate', value: 'inventoryProfileCreate' },
    { name: 'InventoryProfileDelete', value: 'inventoryProfileDelete' },
    { name: 'InventoryProfileRead', value: 'inventoryProfileRead' },
    { name: 'InventoryProfileReadById', value: 'inventoryProfileReadById' },
    { name: 'InventoryProfileUpdate', value: 'inventoryProfileUpdate' },
    { name: 'InventoryRead', value: 'inventoryRead' },
    { name: 'InventoryReadById', value: 'inventoryReadById' },
    { name: 'InventoryStockCreate', value: 'inventoryStockCreate' },
    { name: 'InventoryStockDelete', value: 'inventoryStockDelete' },
    { name: 'InventoryStockOpCreate', value: 'inventoryStockOpCreate' },
    { name: 'InventoryStockRead', value: 'inventoryStockRead' },
    { name: 'InventoryStockReadById', value: 'inventoryStockReadById' },
    { name: 'InventoryStockUpdate', value: 'inventoryStockUpdate' },
    { name: 'InventoryUpdate', value: 'inventoryUpdate' },
    { name: 'LotCreate', value: 'lotCreate' },
    { name: 'LotDelete', value: 'lotDelete' },
    { name: 'LotRead', value: 'lotRead' },
    { name: 'LotReadById', value: 'lotReadById' },
    { name: 'LotUpdate', value: 'lotUpdate' },
    { name: 'MovingOrderCreate', value: 'movingOrderCreate' },
    { name: 'MovingOrderDelete', value: 'movingOrderDelete' },
    { name: 'MovingOrderItemDelete', value: 'movingOrderItemDelete' },
    { name: 'MovingOrderItemOpFinish', value: 'movingOrderItemOpFinish' },
    { name: 'MovingOrderItemOpLoad', value: 'movingOrderItemOpLoad' },
    { name: 'MovingOrderItemOpStart', value: 'movingOrderItemOpStart' },
    { name: 'MovingOrderItemOpStartRevert', value: 'movingOrderItemOpStartRevert' },
    { name: 'MovingOrderItemRead', value: 'movingOrderItemRead' },
    { name: 'MovingOrderItemReadById', value: 'movingOrderItemReadById' },
    { name: 'MovingOrderItemUpdate', value: 'movingOrderItemUpdate' },
    { name: 'MovingOrderOpAllocateStock', value: 'movingOrderOpAllocateStock' },
    { name: 'MovingOrderOpApprove', value: 'movingOrderOpApprove' },
    { name: 'MovingOrderOpApproveRevert', value: 'movingOrderOpApproveRevert' },
    { name: 'MovingOrderOpFinish', value: 'movingOrderOpFinish' },
    { name: 'MovingOrderOpPrepare', value: 'movingOrderOpPrepare' },
    { name: 'MovingOrderOpPrepareRevert', value: 'movingOrderOpPrepareRevert' },
    { name: 'MovingOrderOpStart', value: 'movingOrderOpStart' },
    { name: 'MovingOrderOpStartRevert', value: 'movingOrderOpStartRevert' },
    { name: 'MovingOrderOpUnload', value: 'movingOrderOpUnload' },
    { name: 'MovingOrderRead', value: 'movingOrderRead' },
    { name: 'MovingOrderReadById', value: 'movingOrderReadById' },
    { name: 'MovingOrderUpdate', value: 'movingOrderUpdate' },
    { name: 'OutgoingListDelete', value: 'outgoingListDelete' },
    { name: 'OutgoingListOpCreateFromReservation', value: 'outgoingListOpCreateFromReservation' },
    { name: 'OutgoingListOpMerge', value: 'outgoingListOpMerge' },
    { name: 'OutgoingListOpOutgoingInvoiceCreate', value: 'outgoingListOpOutgoingInvoiceCreate' },
    { name: 'OutgoingListOpOutgoingInvoiceCreateRevert', value: 'outgoingListOpOutgoingInvoiceCreateRevert' },
    { name: 'OutgoingListOpPacked', value: 'outgoingListOpPacked' },
    { name: 'OutgoingListOpPackedRevert', value: 'outgoingListOpPackedRevert' },
    { name: 'OutgoingListOpVolumeCreateAuto', value: 'outgoingListOpVolumeCreateAuto' },
    { name: 'OutgoingListRead', value: 'outgoingListRead' },
    { name: 'OutgoingListReadById', value: 'outgoingListReadById' },
    { name: 'PickingOrderCreate', value: 'pickingOrderCreate' },
    { name: 'PickingOrderDelete', value: 'pickingOrderDelete' },
    { name: 'PickingOrderItemCreate', value: 'pickingOrderItemCreate' },
    { name: 'PickingOrderItemDelete', value: 'pickingOrderItemDelete' },
    { name: 'PickingOrderItemRead', value: 'pickingOrderItemRead' },
    { name: 'PickingOrderItemReadById', value: 'pickingOrderItemReadById' },
    { name: 'PickingOrderItemUpdate', value: 'pickingOrderItemUpdate' },
    { name: 'PickingOrderOpApprove', value: 'pickingOrderOpApprove' },
    { name: 'PickingOrderOpApproveRevert', value: 'pickingOrderOpApproveRevert' },
    { name: 'PickingOrderOpCreate', value: 'pickingOrderOpCreate' },
    { name: 'PickingOrderOpDistribute', value: 'pickingOrderOpDistribute' },
    { name: 'PickingOrderOpDistributeAuto', value: 'pickingOrderOpDistributeAuto' },
    { name: 'PickingOrderOpDistributeRevert', value: 'pickingOrderOpDistributeRevert' },
    { name: 'PickingOrderOpFinish', value: 'pickingOrderOpFinish' },
    { name: 'PickingOrderOpGroup', value: 'pickingOrderOpGroup' },
    { name: 'PickingOrderOpGroupRevert', value: 'pickingOrderOpGroupRevert' },
    { name: 'PickingOrderOpPrepare', value: 'pickingOrderOpPrepare' },
    { name: 'PickingOrderOpPrepareRevert', value: 'pickingOrderOpPrepareRevert' },
    { name: 'PickingOrderOpReservationFinish', value: 'pickingOrderOpReservationFinish' },
    { name: 'PickingOrderOpReservationFinishRevert', value: 'pickingOrderOpReservationFinishRevert' },
    { name: 'PickingOrderOpUngroup', value: 'pickingOrderOpUngroup' },
    { name: 'PickingOrderOpUngroupDivergent', value: 'pickingOrderOpUngroupDivergent' },
    { name: 'PickingOrderOpUngroupRevert', value: 'pickingOrderOpUngroupRevert' },
    { name: 'PickingOrderRead', value: 'pickingOrderRead' },
    { name: 'PickingOrderReadById', value: 'pickingOrderReadById' },
    { name: 'PickingOrderUpdate', value: 'pickingOrderUpdate' },
    { name: 'PickingProfileCreate', value: 'pickingProfileCreate' },
    { name: 'PickingProfileDelete', value: 'pickingProfileDelete' },
    { name: 'PickingProfileRead', value: 'pickingProfileRead' },
    { name: 'PickingProfileReadById', value: 'pickingProfileReadById' },
    { name: 'PickingProfileUpdate', value: 'pickingProfileUpdate' },
    { name: 'QualityCreate', value: 'qualityCreate' },
    { name: 'QualityDelete', value: 'qualityDelete' },
    { name: 'QualityRead', value: 'qualityRead' },
    { name: 'QualityReadById', value: 'qualityReadById' },
    { name: 'QualityUpdate', value: 'qualityUpdate' },
    { name: 'ReservationCreate', value: 'reservationCreate' },
    { name: 'ReservationDelete', value: 'reservationDelete' },
    { name: 'ReservationItemRead', value: 'reservationItemRead' },
    { name: 'ReservationItemReadById', value: 'reservationItemReadById' },
    { name: 'ReservationOpAllocate', value: 'reservationOpAllocate' },
    { name: 'ReservationOpAllocateAuto', value: 'reservationOpAllocateAuto' },
    { name: 'ReservationOpAllocateAutoRevert', value: 'reservationOpAllocateAutoRevert' },
    { name: 'ReservationOpAllocateRevert', value: 'reservationOpAllocateRevert' },
    { name: 'ReservationOpAllocateStock', value: 'reservationOpAllocateStock' },
    { name: 'ReservationOpAllocateStockRevert', value: 'reservationOpAllocateStockRevert' },
    { name: 'ReservationOpApprove', value: 'reservationOpApprove' },
    { name: 'ReservationOpApproveRevert', value: 'reservationOpApproveRevert' },
    { name: 'ReservationOpCreate', value: 'reservationOpCreate' },
    { name: 'ReservationOpFinish', value: 'reservationOpFinish' },
    { name: 'ReservationOpFinishDivergent', value: 'reservationOpFinishDivergent' },
    { name: 'ReservationOpFinishRevert', value: 'reservationOpFinishRevert' },
    { name: 'ReservationOpPrepare', value: 'reservationOpPrepare' },
    { name: 'ReservationOpPrepareRevert', value: 'reservationOpPrepareRevert' },
    { name: 'ReservationOpStart', value: 'reservationOpStart' },
    { name: 'ReservationOpStartRevert', value: 'reservationOpStartRevert' },
    { name: 'ReservationRead', value: 'reservationRead' },
    { name: 'ReservationReadById', value: 'reservationReadById' },
    { name: 'ReservationTargetCreate', value: 'reservationTargetCreate' },
    { name: 'ReservationTargetDelete', value: 'reservationTargetDelete' },
    { name: 'ReservationTargetRead', value: 'reservationTargetRead' },
    { name: 'ReservationTargetReadById', value: 'reservationTargetReadById' },
    { name: 'ReservationTargetUpdate', value: 'reservationTargetUpdate' },
    { name: 'ReservationUpdate', value: 'reservationUpdate' },
    { name: 'SerialCreate', value: 'serialCreate' },
    { name: 'SerialDelete', value: 'serialDelete' },
    { name: 'SerialRead', value: 'serialRead' },
    { name: 'SerialReadById', value: 'serialReadById' },
    { name: 'SerialUpdate', value: 'serialUpdate' },
    { name: 'StockAvailabilityRead', value: 'stockAvailabilityRead' },
    { name: 'StockClusterCreate', value: 'stockClusterCreate' },
    { name: 'StockClusterDelete', value: 'stockClusterDelete' },
    { name: 'StockClusterRead', value: 'stockClusterRead' },
    { name: 'StockClusterReadById', value: 'stockClusterReadById' },
    { name: 'StockClusterUpdate', value: 'stockClusterUpdate' },
    { name: 'StockManagementCreate', value: 'stockManagementCreate' },
    { name: 'StockManagementDelete', value: 'stockManagementDelete' },
    { name: 'StockManagementItemCreate', value: 'stockManagementItemCreate' },
    { name: 'StockManagementItemDelete', value: 'stockManagementItemDelete' },
    { name: 'StockManagementItemRead', value: 'stockManagementItemRead' },
    { name: 'StockManagementItemReadById', value: 'stockManagementItemReadById' },
    { name: 'StockManagementItemUpdate', value: 'stockManagementItemUpdate' },
    { name: 'StockManagementOpImport', value: 'stockManagementOpImport' },
    { name: 'StockManagementOpUpdateAverageDailyConsumption', value: 'stockManagementOpUpdateAverageDailyConsumption' },
    { name: 'StockManagementRead', value: 'stockManagementRead' },
    { name: 'StockManagementReadById', value: 'stockManagementReadById' },
    { name: 'StockManagementUpdate', value: 'stockManagementUpdate' },
    { name: 'StockOpBarcode', value: 'stockOpBarcode' },
    { name: 'StockOpCompensate', value: 'stockOpCompensate' },
    { name: 'StockOpUpdate', value: 'stockOpUpdate' },
    { name: 'StockRead', value: 'stockRead' },
    { name: 'StockReadById', value: 'stockReadById' },
    { name: 'StockTransactionOpRevert', value: 'stockTransactionOpRevert' },
    { name: 'StockTransactionRead', value: 'stockTransactionRead' },
    { name: 'StockTransactionReadById', value: 'stockTransactionReadById' },
    { name: 'VolumeCreate', value: 'volumeCreate' },
    { name: 'VolumeDelete', value: 'volumeDelete' },
    { name: 'VolumeItemCreate', value: 'volumeItemCreate' },
    { name: 'VolumeItemDelete', value: 'volumeItemDelete' },
    { name: 'VolumeItemRead', value: 'volumeItemRead' },
    { name: 'VolumeItemReadById', value: 'volumeItemReadById' },
    { name: 'VolumeOpCheck', value: 'volumeOpCheck' },
    { name: 'VolumeOpCheckRevert', value: 'volumeOpCheckRevert' },
    { name: 'VolumeOpCreate', value: 'volumeOpCreate' },
    { name: 'VolumeOpHandlingUnitSet', value: 'volumeOpHandlingUnitSet' },
    { name: 'VolumeRead', value: 'volumeRead' },
    { name: 'VolumeReadById', value: 'volumeReadById' },
    { name: 'VolumeUpdate', value: 'volumeUpdate' },
    { name: 'WarehouseCreate', value: 'warehouseCreate' },
    { name: 'WarehouseDelete', value: 'warehouseDelete' },
    { name: 'WarehouseRead', value: 'warehouseRead' },
    { name: 'WarehouseReadById', value: 'warehouseReadById' },
    { name: 'WarehouseUpdate', value: 'warehouseUpdate' }
  ],
  default: 'addressCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
