import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'PriceFormationCreate', value: 'priceFormationCreate' },
    { name: 'PriceFormationDelete', value: 'priceFormationDelete' },
    { name: 'PriceFormationItemCreate', value: 'priceFormationItemCreate' },
    { name: 'PriceFormationItemDelete', value: 'priceFormationItemDelete' },
    { name: 'PriceFormationItemRead', value: 'priceFormationItemRead' },
    { name: 'PriceFormationItemReadById', value: 'priceFormationItemReadById' },
    { name: 'PriceFormationItemUpdate', value: 'priceFormationItemUpdate' },
    { name: 'PriceFormationOpCalculate', value: 'priceFormationOpCalculate' },
    { name: 'PriceFormationOpClone', value: 'priceFormationOpClone' },
    { name: 'PriceFormationOpSimulation', value: 'priceFormationOpSimulation' },
    { name: 'PriceFormationRead', value: 'priceFormationRead' },
    { name: 'PriceFormationReadById', value: 'priceFormationReadById' },
    { name: 'PriceFormationUpdate', value: 'priceFormationUpdate' },
    { name: 'PriceListCreate', value: 'priceListCreate' },
    { name: 'PriceListDelete', value: 'priceListDelete' },
    { name: 'PriceListItemCreate', value: 'priceListItemCreate' },
    { name: 'PriceListItemDelete', value: 'priceListItemDelete' },
    { name: 'PriceListItemRead', value: 'priceListItemRead' },
    { name: 'PriceListItemReadById', value: 'priceListItemReadById' },
    { name: 'PriceListItemUpdate', value: 'priceListItemUpdate' },
    { name: 'PriceListRead', value: 'priceListRead' },
    { name: 'PriceListReadById', value: 'priceListReadById' },
    { name: 'PriceListUpdate', value: 'priceListUpdate' },
    { name: 'QuoteCreate', value: 'quoteCreate' },
    { name: 'QuoteDelete', value: 'quoteDelete' },
    { name: 'QuoteItemCreate', value: 'quoteItemCreate' },
    { name: 'QuoteItemDelete', value: 'quoteItemDelete' },
    { name: 'QuoteItemOpReject', value: 'quoteItemOpReject' },
    { name: 'QuoteItemOpRejectRevert', value: 'quoteItemOpRejectRevert' },
    { name: 'QuoteItemProposalCreate', value: 'quoteItemProposalCreate' },
    { name: 'QuoteItemProposalDelete', value: 'quoteItemProposalDelete' },
    { name: 'QuoteItemProposalOpApprove', value: 'quoteItemProposalOpApprove' },
    { name: 'QuoteItemProposalOpApproveRevert', value: 'quoteItemProposalOpApproveRevert' },
    { name: 'QuoteItemProposalOpReject', value: 'quoteItemProposalOpReject' },
    { name: 'QuoteItemProposalOpRejectRevert', value: 'quoteItemProposalOpRejectRevert' },
    { name: 'QuoteItemProposalRead', value: 'quoteItemProposalRead' },
    { name: 'QuoteItemProposalReadById', value: 'quoteItemProposalReadById' },
    { name: 'QuoteItemProposalUpdate', value: 'quoteItemProposalUpdate' },
    { name: 'QuoteItemRead', value: 'quoteItemRead' },
    { name: 'QuoteItemReadById', value: 'quoteItemReadById' },
    { name: 'QuoteItemUpdate', value: 'quoteItemUpdate' },
    { name: 'QuoteOpApprove', value: 'quoteOpApprove' },
    { name: 'QuoteOpApproveRevert', value: 'quoteOpApproveRevert' },
    { name: 'QuoteOpCancel', value: 'quoteOpCancel' },
    { name: 'QuoteOpCancelRevert', value: 'quoteOpCancelRevert' },
    { name: 'QuoteOpCreate', value: 'quoteOpCreate' },
    { name: 'QuoteOpFill', value: 'quoteOpFill' },
    { name: 'QuoteOpFillRevert', value: 'quoteOpFillRevert' },
    { name: 'QuoteOpPrepare', value: 'quoteOpPrepare' },
    { name: 'QuoteOpPrepareRevert', value: 'quoteOpPrepareRevert' },
    { name: 'QuoteOpReject', value: 'quoteOpReject' },
    { name: 'QuoteOpRejectRevert', value: 'quoteOpRejectRevert' },
    { name: 'QuoteOpStart', value: 'quoteOpStart' },
    { name: 'QuoteOpStartRevert', value: 'quoteOpStartRevert' },
    { name: 'QuoteOpSubmit', value: 'quoteOpSubmit' },
    { name: 'QuoteOpSubmitRevert', value: 'quoteOpSubmitRevert' },
    { name: 'QuoteRead', value: 'quoteRead' },
    { name: 'QuoteReadById', value: 'quoteReadById' },
    { name: 'QuoteUpdate', value: 'quoteUpdate' },
    { name: 'SaleCreate', value: 'saleCreate' },
    { name: 'SaleDelete', value: 'saleDelete' },
    { name: 'SaleItemCreate', value: 'saleItemCreate' },
    { name: 'SaleItemDelete', value: 'saleItemDelete' },
    { name: 'SaleItemOpUpdatePrepared', value: 'saleItemOpUpdatePrepared' },
    { name: 'SaleItemRead', value: 'saleItemRead' },
    { name: 'SaleItemReadById', value: 'saleItemReadById' },
    { name: 'SaleItemUpdate', value: 'saleItemUpdate' },
    { name: 'SaleOpApprove', value: 'saleOpApprove' },
    { name: 'SaleOpApproveRevert', value: 'saleOpApproveRevert' },
    { name: 'SaleOpApproveUnconditionally', value: 'saleOpApproveUnconditionally' },
    { name: 'SaleOpCancel', value: 'saleOpCancel' },
    { name: 'SaleOpCancelRevert', value: 'saleOpCancelRevert' },
    { name: 'SaleOpClone', value: 'saleOpClone' },
    { name: 'SaleOpCreate', value: 'saleOpCreate' },
    { name: 'SaleOpFinishRevert', value: 'saleOpFinishRevert' },
    { name: 'SaleOpForwardAuto', value: 'saleOpForwardAuto' },
    { name: 'SaleOpMerge', value: 'saleOpMerge' },
    { name: 'SaleOpMergeRevert', value: 'saleOpMergeRevert' },
    { name: 'SaleOpPickingOrderCreate', value: 'saleOpPickingOrderCreate' },
    { name: 'SaleOpPickingOrderCreateRevert', value: 'saleOpPickingOrderCreateRevert' },
    { name: 'SaleOpPrepare', value: 'saleOpPrepare' },
    { name: 'SaleOpPrepareRevert', value: 'saleOpPrepareRevert' },
    { name: 'SaleOpShipmentAssign', value: 'saleOpShipmentAssign' },
    { name: 'SaleOpShipmentAssignRevert', value: 'saleOpShipmentAssignRevert' },
    { name: 'SaleOpSplit', value: 'saleOpSplit' },
    { name: 'SaleOpTaxationCalc', value: 'saleOpTaxationCalc' },
    { name: 'SaleOpUpdatePrepared', value: 'saleOpUpdatePrepared' },
    { name: 'SalePaymentCreate', value: 'salePaymentCreate' },
    { name: 'SalePaymentDelete', value: 'salePaymentDelete' },
    { name: 'SalePaymentRead', value: 'salePaymentRead' },
    { name: 'SalePaymentReadById', value: 'salePaymentReadById' },
    { name: 'SalePaymentUpdate', value: 'salePaymentUpdate' },
    { name: 'SaleProfileCreate', value: 'saleProfileCreate' },
    { name: 'SaleProfileDelete', value: 'saleProfileDelete' },
    { name: 'SaleProfileRead', value: 'saleProfileRead' },
    { name: 'SaleProfileReadById', value: 'saleProfileReadById' },
    { name: 'SaleProfileUpdate', value: 'saleProfileUpdate' },
    { name: 'SaleRead', value: 'saleRead' },
    { name: 'SaleReadById', value: 'saleReadById' },
    { name: 'SaleUpdate', value: 'saleUpdate' }
  ],
  default: 'priceFormationCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
