import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'ClearanceCreate', value: 'clearanceCreate' },
    { name: 'ClearanceDelete', value: 'clearanceDelete' },
    { name: 'ClearanceItemCreate', value: 'clearanceItemCreate' },
    { name: 'ClearanceItemDelete', value: 'clearanceItemDelete' },
    { name: 'ClearanceItemRead', value: 'clearanceItemRead' },
    { name: 'ClearanceItemReadById', value: 'clearanceItemReadById' },
    { name: 'ClearanceItemUpdate', value: 'clearanceItemUpdate' },
    { name: 'ClearanceOpApprove', value: 'clearanceOpApprove' },
    { name: 'ClearanceOpApproveRevert', value: 'clearanceOpApproveRevert' },
    { name: 'ClearanceOpPrepare', value: 'clearanceOpPrepare' },
    { name: 'ClearanceOpPrepareRevert', value: 'clearanceOpPrepareRevert' },
    { name: 'ClearanceRead', value: 'clearanceRead' },
    { name: 'ClearanceReadById', value: 'clearanceReadById' },
    { name: 'ClearanceUpdate', value: 'clearanceUpdate' },
    { name: 'ContractCreate', value: 'contractCreate' },
    { name: 'ContractDelete', value: 'contractDelete' },
    { name: 'ContractItemCreate', value: 'contractItemCreate' },
    { name: 'ContractItemDelete', value: 'contractItemDelete' },
    { name: 'ContractItemRead', value: 'contractItemRead' },
    { name: 'ContractItemReadById', value: 'contractItemReadById' },
    { name: 'ContractItemUpdate', value: 'contractItemUpdate' },
    { name: 'ContractOpApprove', value: 'contractOpApprove' },
    { name: 'ContractOpApproveRevert', value: 'contractOpApproveRevert' },
    { name: 'ContractOpPrepare', value: 'contractOpPrepare' },
    { name: 'ContractOpPrepareRevert', value: 'contractOpPrepareRevert' },
    { name: 'ContractPaymentCreate', value: 'contractPaymentCreate' },
    { name: 'ContractPaymentDelete', value: 'contractPaymentDelete' },
    { name: 'ContractPaymentOpApprove', value: 'contractPaymentOpApprove' },
    { name: 'ContractPaymentOpApproveRevert', value: 'contractPaymentOpApproveRevert' },
    { name: 'ContractPaymentOpPrepare', value: 'contractPaymentOpPrepare' },
    { name: 'ContractPaymentOpPrepareRevert', value: 'contractPaymentOpPrepareRevert' },
    { name: 'ContractPaymentRead', value: 'contractPaymentRead' },
    { name: 'ContractPaymentReadById', value: 'contractPaymentReadById' },
    { name: 'ContractPaymentUpdate', value: 'contractPaymentUpdate' },
    { name: 'ContractRead', value: 'contractRead' },
    { name: 'ContractReadById', value: 'contractReadById' },
    { name: 'ContractUpdate', value: 'contractUpdate' },
    { name: 'CostAllocationCreate', value: 'costAllocationCreate' },
    { name: 'CostAllocationDelete', value: 'costAllocationDelete' },
    { name: 'CostAllocationRead', value: 'costAllocationRead' },
    { name: 'CostAllocationReadById', value: 'costAllocationReadById' },
    { name: 'CostAllocationUpdate', value: 'costAllocationUpdate' },
    { name: 'CostCreate', value: 'costCreate' },
    { name: 'CostDelete', value: 'costDelete' },
    { name: 'CostRead', value: 'costRead' },
    { name: 'CostReadById', value: 'costReadById' },
    { name: 'CostUpdate', value: 'costUpdate' },
    { name: 'ExchangeContractCreate', value: 'exchangeContractCreate' },
    { name: 'ExchangeContractDelete', value: 'exchangeContractDelete' },
    { name: 'ExchangeContractOpApprove', value: 'exchangeContractOpApprove' },
    { name: 'ExchangeContractOpApproveRevert', value: 'exchangeContractOpApproveRevert' },
    { name: 'ExchangeContractOpPrepare', value: 'exchangeContractOpPrepare' },
    { name: 'ExchangeContractOpPrepareRevert', value: 'exchangeContractOpPrepareRevert' },
    { name: 'ExchangeContractPaymentCreate', value: 'exchangeContractPaymentCreate' },
    { name: 'ExchangeContractPaymentDelete', value: 'exchangeContractPaymentDelete' },
    { name: 'ExchangeContractPaymentOpApprove', value: 'exchangeContractPaymentOpApprove' },
    { name: 'ExchangeContractPaymentOpApproveRevert', value: 'exchangeContractPaymentOpApproveRevert' },
    { name: 'ExchangeContractPaymentOpPrepare', value: 'exchangeContractPaymentOpPrepare' },
    { name: 'ExchangeContractPaymentOpPrepareRevert', value: 'exchangeContractPaymentOpPrepareRevert' },
    { name: 'ExchangeContractPaymentRead', value: 'exchangeContractPaymentRead' },
    { name: 'ExchangeContractPaymentReadById', value: 'exchangeContractPaymentReadById' },
    { name: 'ExchangeContractPaymentUpdate', value: 'exchangeContractPaymentUpdate' },
    { name: 'ExchangeContractProfileCreate', value: 'exchangeContractProfileCreate' },
    { name: 'ExchangeContractProfileDelete', value: 'exchangeContractProfileDelete' },
    { name: 'ExchangeContractProfileRead', value: 'exchangeContractProfileRead' },
    { name: 'ExchangeContractProfileReadById', value: 'exchangeContractProfileReadById' },
    { name: 'ExchangeContractProfileUpdate', value: 'exchangeContractProfileUpdate' },
    { name: 'ExchangeContractRead', value: 'exchangeContractRead' },
    { name: 'ExchangeContractReadById', value: 'exchangeContractReadById' },
    { name: 'ExchangeContractUpdate', value: 'exchangeContractUpdate' },
    { name: 'ShipmentContainerCreate', value: 'shipmentContainerCreate' },
    { name: 'ShipmentContainerDelete', value: 'shipmentContainerDelete' },
    { name: 'ShipmentContainerRead', value: 'shipmentContainerRead' },
    { name: 'ShipmentContainerReadById', value: 'shipmentContainerReadById' },
    { name: 'ShipmentContainerUpdate', value: 'shipmentContainerUpdate' },
    { name: 'ShipmentCreate', value: 'shipmentCreate' },
    { name: 'ShipmentDelete', value: 'shipmentDelete' },
    { name: 'ShipmentItemCreate', value: 'shipmentItemCreate' },
    { name: 'ShipmentItemDelete', value: 'shipmentItemDelete' },
    { name: 'ShipmentItemRead', value: 'shipmentItemRead' },
    { name: 'ShipmentItemReadById', value: 'shipmentItemReadById' },
    { name: 'ShipmentItemUpdate', value: 'shipmentItemUpdate' },
    { name: 'ShipmentOpApprove', value: 'shipmentOpApprove' },
    { name: 'ShipmentOpApproveRevert', value: 'shipmentOpApproveRevert' },
    { name: 'ShipmentOpPrepare', value: 'shipmentOpPrepare' },
    { name: 'ShipmentOpPrepareRevert', value: 'shipmentOpPrepareRevert' },
    { name: 'ShipmentRead', value: 'shipmentRead' },
    { name: 'ShipmentReadById', value: 'shipmentReadById' },
    { name: 'ShipmentUpdate', value: 'shipmentUpdate' }
  ],
  default: 'clearanceCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
