import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'PriceListCreate', value: 'priceListCreate' },
    { name: 'PriceListDelete', value: 'priceListDelete' },
    { name: 'PriceListItemCreate', value: 'priceListItemCreate' },
    { name: 'PriceListItemDelete', value: 'priceListItemDelete' },
    { name: 'PriceListItemRead', value: 'priceListItemRead' },
    { name: 'PriceListItemReadById', value: 'priceListItemReadById' },
    { name: 'PriceListItemUpdate', value: 'priceListItemUpdate' },
    { name: 'PriceListRead', value: 'priceListRead' },
    { name: 'PriceListReadById', value: 'priceListReadById' },
    { name: 'PriceListUpdate', value: 'priceListUpdate' },
    { name: 'ProposalCreate', value: 'proposalCreate' },
    { name: 'ProposalDelete', value: 'proposalDelete' },
    { name: 'ProposalItemCreate', value: 'proposalItemCreate' },
    { name: 'ProposalItemDelete', value: 'proposalItemDelete' },
    { name: 'ProposalItemOpApprove', value: 'proposalItemOpApprove' },
    { name: 'ProposalItemOpApproveRevert', value: 'proposalItemOpApproveRevert' },
    { name: 'ProposalItemOpDisapprove', value: 'proposalItemOpDisapprove' },
    { name: 'ProposalItemOpDisapproveRevert', value: 'proposalItemOpDisapproveRevert' },
    { name: 'ProposalItemRead', value: 'proposalItemRead' },
    { name: 'ProposalItemReadById', value: 'proposalItemReadById' },
    { name: 'ProposalItemUpdate', value: 'proposalItemUpdate' },
    { name: 'ProposalOpCancel', value: 'proposalOpCancel' },
    { name: 'ProposalOpCancelRevert', value: 'proposalOpCancelRevert' },
    { name: 'ProposalOpPrepare', value: 'proposalOpPrepare' },
    { name: 'ProposalOpPrepareRevert', value: 'proposalOpPrepareRevert' },
    { name: 'ProposalRead', value: 'proposalRead' },
    { name: 'ProposalReadById', value: 'proposalReadById' },
    { name: 'ProposalRequestReadById', value: 'proposalRequestReadById' },
    { name: 'ProposalRequestUpdate', value: 'proposalRequestUpdate' },
    { name: 'ProposalUpdate', value: 'proposalUpdate' },
    { name: 'PurchaseCreate', value: 'purchaseCreate' },
    { name: 'PurchaseDelete', value: 'purchaseDelete' },
    { name: 'PurchaseItemCreate', value: 'purchaseItemCreate' },
    { name: 'PurchaseItemDelete', value: 'purchaseItemDelete' },
    { name: 'PurchaseItemRead', value: 'purchaseItemRead' },
    { name: 'PurchaseItemReadById', value: 'purchaseItemReadById' },
    { name: 'PurchaseItemUpdate', value: 'purchaseItemUpdate' },
    { name: 'PurchaseOpApprove', value: 'purchaseOpApprove' },
    { name: 'PurchaseOpApproveRevert', value: 'purchaseOpApproveRevert' },
    { name: 'PurchaseOpApproveUnconditionally', value: 'purchaseOpApproveUnconditionally' },
    { name: 'PurchaseOpCancel', value: 'purchaseOpCancel' },
    { name: 'PurchaseOpCancelRevert', value: 'purchaseOpCancelRevert' },
    { name: 'PurchaseOpClone', value: 'purchaseOpClone' },
    { name: 'PurchaseOpCreate', value: 'purchaseOpCreate' },
    { name: 'PurchaseOpFinish', value: 'purchaseOpFinish' },
    { name: 'PurchaseOpFinishRevert', value: 'purchaseOpFinishRevert' },
    { name: 'PurchaseOpMerge', value: 'purchaseOpMerge' },
    { name: 'PurchaseOpPrepare', value: 'purchaseOpPrepare' },
    { name: 'PurchaseOpPrepareRevert', value: 'purchaseOpPrepareRevert' },
    { name: 'PurchaseOpSplit', value: 'purchaseOpSplit' },
    { name: 'PurchaseOpTaxationCalc', value: 'purchaseOpTaxationCalc' },
    { name: 'PurchaseOpUpdatePrepared', value: 'purchaseOpUpdatePrepared' },
    { name: 'PurchasePaymentCreate', value: 'purchasePaymentCreate' },
    { name: 'PurchasePaymentDelete', value: 'purchasePaymentDelete' },
    { name: 'PurchasePaymentRead', value: 'purchasePaymentRead' },
    { name: 'PurchasePaymentReadById', value: 'purchasePaymentReadById' },
    { name: 'PurchasePaymentUpdate', value: 'purchasePaymentUpdate' },
    { name: 'PurchaseProfileCreate', value: 'purchaseProfileCreate' },
    { name: 'PurchaseProfileDelete', value: 'purchaseProfileDelete' },
    { name: 'PurchaseProfileRead', value: 'purchaseProfileRead' },
    { name: 'PurchaseProfileReadById', value: 'purchaseProfileReadById' },
    { name: 'PurchaseProfileUpdate', value: 'purchaseProfileUpdate' },
    { name: 'PurchaseRead', value: 'purchaseRead' },
    { name: 'PurchaseReadById', value: 'purchaseReadById' },
    { name: 'PurchaseUpdate', value: 'purchaseUpdate' },
    { name: 'QuoteCreate', value: 'quoteCreate' },
    { name: 'QuoteDelete', value: 'quoteDelete' },
    { name: 'QuoteItemCreate', value: 'quoteItemCreate' },
    { name: 'QuoteItemDelete', value: 'quoteItemDelete' },
    { name: 'QuoteItemRead', value: 'quoteItemRead' },
    { name: 'QuoteItemReadById', value: 'quoteItemReadById' },
    { name: 'QuoteItemUpdate', value: 'quoteItemUpdate' },
    { name: 'QuoteOpApprove', value: 'quoteOpApprove' },
    { name: 'QuoteOpApproveRevert', value: 'quoteOpApproveRevert' },
    { name: 'QuoteOpCancel', value: 'quoteOpCancel' },
    { name: 'QuoteOpCancelRevert', value: 'quoteOpCancelRevert' },
    { name: 'QuoteOpCreate', value: 'quoteOpCreate' },
    { name: 'QuoteOpFinish', value: 'quoteOpFinish' },
    { name: 'QuoteOpFinishRevert', value: 'quoteOpFinishRevert' },
    { name: 'QuoteOpPrepare', value: 'quoteOpPrepare' },
    { name: 'QuoteOpPrepareRevert', value: 'quoteOpPrepareRevert' },
    { name: 'QuoteRead', value: 'quoteRead' },
    { name: 'QuoteReadById', value: 'quoteReadById' },
    { name: 'QuoteUpdate', value: 'quoteUpdate' }
  ],
  default: 'priceListCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
