import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'ContractBillingCreate', value: 'contractBillingCreate' },
    { name: 'ContractBillingDelete', value: 'contractBillingDelete' },
    { name: 'ContractBillingOpApprove', value: 'contractBillingOpApprove' },
    { name: 'ContractBillingOpApproveRevert', value: 'contractBillingOpApproveRevert' },
    { name: 'ContractBillingOpCreate', value: 'contractBillingOpCreate' },
    { name: 'ContractBillingOpCreateInvoice', value: 'contractBillingOpCreateInvoice' },
    { name: 'ContractBillingOpCreateInvoiceRevert', value: 'contractBillingOpCreateInvoiceRevert' },
    { name: 'ContractBillingOpCreateRevert', value: 'contractBillingOpCreateRevert' },
    { name: 'ContractBillingOpPrepare', value: 'contractBillingOpPrepare' },
    { name: 'ContractBillingOpPrepareRevert', value: 'contractBillingOpPrepareRevert' },
    { name: 'ContractBillingRead', value: 'contractBillingRead' },
    { name: 'ContractBillingReadById', value: 'contractBillingReadById' },
    { name: 'ContractBillingUpdate', value: 'contractBillingUpdate' },
    { name: 'ContractCreate', value: 'contractCreate' },
    { name: 'ContractDelete', value: 'contractDelete' },
    { name: 'ContractIndexCreate', value: 'contractIndexCreate' },
    { name: 'ContractIndexDelete', value: 'contractIndexDelete' },
    { name: 'ContractIndexRead', value: 'contractIndexRead' },
    { name: 'ContractIndexReadById', value: 'contractIndexReadById' },
    { name: 'ContractIndexUpdate', value: 'contractIndexUpdate' },
    { name: 'ContractItemCreate', value: 'contractItemCreate' },
    { name: 'ContractItemDelete', value: 'contractItemDelete' },
    { name: 'ContractItemRead', value: 'contractItemRead' },
    { name: 'ContractItemReadById', value: 'contractItemReadById' },
    { name: 'ContractItemUpdate', value: 'contractItemUpdate' },
    { name: 'ContractOpAdjust', value: 'contractOpAdjust' },
    { name: 'ContractOpApprove', value: 'contractOpApprove' },
    { name: 'ContractOpApproveRevert', value: 'contractOpApproveRevert' },
    { name: 'ContractOpCancel', value: 'contractOpCancel' },
    { name: 'ContractOpCancelRevert', value: 'contractOpCancelRevert' },
    { name: 'ContractOpCreate', value: 'contractOpCreate' },
    { name: 'ContractOpPrepare', value: 'contractOpPrepare' },
    { name: 'ContractOpPrepareRevert', value: 'contractOpPrepareRevert' },
    { name: 'ContractProfileCreate', value: 'contractProfileCreate' },
    { name: 'ContractProfileDelete', value: 'contractProfileDelete' },
    { name: 'ContractProfileRead', value: 'contractProfileRead' },
    { name: 'ContractProfileReadById', value: 'contractProfileReadById' },
    { name: 'ContractProfileUpdate', value: 'contractProfileUpdate' },
    { name: 'ContractRead', value: 'contractRead' },
    { name: 'ContractReadById', value: 'contractReadById' },
    { name: 'ContractUpdate', value: 'contractUpdate' }
  ],
  default: 'contractBillingCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
