import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'BatchRequestCreate', value: 'batchRequestCreate' },
    { name: 'BatchRequestDelete', value: 'batchRequestDelete' },
    { name: 'BatchRequestOpAddInstructions', value: 'batchRequestOpAddInstructions' },
    { name: 'BatchRequestOpApprove', value: 'batchRequestOpApprove' },
    { name: 'BatchRequestOpApproveRevert', value: 'batchRequestOpApproveRevert' },
    { name: 'BatchRequestOpCreateFile', value: 'batchRequestOpCreateFile' },
    { name: 'BatchRequestOpPrepare', value: 'batchRequestOpPrepare' },
    { name: 'BatchRequestOpPrepareRevert', value: 'batchRequestOpPrepareRevert' },
    { name: 'BatchRequestOpSend', value: 'batchRequestOpSend' },
    { name: 'BatchRequestOpSendRevert', value: 'batchRequestOpSendRevert' },
    { name: 'BatchRequestRead', value: 'batchRequestRead' },
    { name: 'BatchRequestReadById', value: 'batchRequestReadById' },
    { name: 'BatchRequestUpdate', value: 'batchRequestUpdate' },
    { name: 'BatchResponseDelete', value: 'batchResponseDelete' },
    { name: 'BatchResponseOpApprove', value: 'batchResponseOpApprove' },
    { name: 'BatchResponseOpApproveRevert', value: 'batchResponseOpApproveRevert' },
    { name: 'BatchResponseOpCreate', value: 'batchResponseOpCreate' },
    { name: 'BatchResponseOpPrepare', value: 'batchResponseOpPrepare' },
    { name: 'BatchResponseOpPrepareRevert', value: 'batchResponseOpPrepareRevert' },
    { name: 'BatchResponseOpProcess', value: 'batchResponseOpProcess' },
    { name: 'BatchResponseRead', value: 'batchResponseRead' },
    { name: 'BatchResponseReadById', value: 'batchResponseReadById' },
    { name: 'InstructionRequestDelete', value: 'instructionRequestDelete' },
    { name: 'InstructionRequestOpAddToBatch', value: 'instructionRequestOpAddToBatch' },
    { name: 'InstructionRequestOpCreate', value: 'instructionRequestOpCreate' },
    { name: 'InstructionRequestOpCreateChangeDueDate', value: 'instructionRequestOpCreateChangeDueDate' },
    { name: 'InstructionRequestOpCreateRegister', value: 'instructionRequestOpCreateRegister' },
    { name: 'InstructionRequestOpCreateUnregister', value: 'instructionRequestOpCreateUnregister' },
    { name: 'InstructionRequestOpRemoveFromBatch', value: 'instructionRequestOpRemoveFromBatch' },
    { name: 'InstructionRequestRead', value: 'instructionRequestRead' },
    { name: 'InstructionRequestReadById', value: 'instructionRequestReadById' },
    { name: 'InstructionRequestUpdate', value: 'instructionRequestUpdate' },
    { name: 'InstructionResponseCreate', value: 'instructionResponseCreate' },
    { name: 'InstructionResponseDelete', value: 'instructionResponseDelete' },
    { name: 'InstructionResponseOpIgnore', value: 'instructionResponseOpIgnore' },
    { name: 'InstructionResponseOpIgnoreRevert', value: 'instructionResponseOpIgnoreRevert' },
    { name: 'InstructionResponseOpProcess', value: 'instructionResponseOpProcess' },
    { name: 'InstructionResponseRead', value: 'instructionResponseRead' },
    { name: 'InstructionResponseReadById', value: 'instructionResponseReadById' },
    { name: 'InstructionResponseUpdate', value: 'instructionResponseUpdate' },
    { name: 'WalletCreate', value: 'walletCreate' },
    { name: 'WalletDelete', value: 'walletDelete' },
    { name: 'WalletOpGetSequence', value: 'walletOpGetSequence' },
    { name: 'WalletRead', value: 'walletRead' },
    { name: 'WalletReadById', value: 'walletReadById' },
    { name: 'WalletUpdate', value: 'walletUpdate' }
  ],
  default: 'batchRequestCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
