import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'CodeConversionCreate', value: 'codeConversionCreate' },
    { name: 'CodeConversionDelete', value: 'codeConversionDelete' },
    { name: 'CodeConversionListCreate', value: 'codeConversionListCreate' },
    { name: 'CodeConversionListDelete', value: 'codeConversionListDelete' },
    { name: 'CodeConversionListRead', value: 'codeConversionListRead' },
    { name: 'CodeConversionListReadById', value: 'codeConversionListReadById' },
    { name: 'CodeConversionListUpdate', value: 'codeConversionListUpdate' },
    { name: 'CodeConversionRead', value: 'codeConversionRead' },
    { name: 'CodeConversionReadById', value: 'codeConversionReadById' },
    { name: 'CodeConversionUpdate', value: 'codeConversionUpdate' },
    { name: 'DimensionCreate', value: 'dimensionCreate' },
    { name: 'DimensionDelete', value: 'dimensionDelete' },
    { name: 'DimensionRead', value: 'dimensionRead' },
    { name: 'DimensionReadById', value: 'dimensionReadById' },
    { name: 'DimensionUpdate', value: 'dimensionUpdate' },
    { name: 'ProductCreate', value: 'productCreate' },
    { name: 'ProductDelete', value: 'productDelete' },
    { name: 'ProductKitComponentCreate', value: 'productKitComponentCreate' },
    { name: 'ProductKitComponentDelete', value: 'productKitComponentDelete' },
    { name: 'ProductKitComponentRead', value: 'productKitComponentRead' },
    { name: 'ProductKitComponentReadById', value: 'productKitComponentReadById' },
    { name: 'ProductKitComponentUpdate', value: 'productKitComponentUpdate' },
    { name: 'ProductOpClone', value: 'productOpClone' },
    { name: 'ProductOpConvertToUnit', value: 'productOpConvertToUnit' },
    { name: 'ProductPackingCreate', value: 'productPackingCreate' },
    { name: 'ProductPackingDelete', value: 'productPackingDelete' },
    { name: 'ProductPackingOpConvertToUnit', value: 'productPackingOpConvertToUnit' },
    { name: 'ProductPackingRead', value: 'productPackingRead' },
    { name: 'ProductPackingReadById', value: 'productPackingReadById' },
    { name: 'ProductPackingUpdate', value: 'productPackingUpdate' },
    { name: 'ProductProfileCreate', value: 'productProfileCreate' },
    { name: 'ProductProfileDelete', value: 'productProfileDelete' },
    { name: 'ProductProfileRead', value: 'productProfileRead' },
    { name: 'ProductProfileReadById', value: 'productProfileReadById' },
    { name: 'ProductProfileUpdate', value: 'productProfileUpdate' },
    { name: 'ProductRead', value: 'productRead' },
    { name: 'ProductReadById', value: 'productReadById' },
    { name: 'ProductUnitConversionCreate', value: 'productUnitConversionCreate' },
    { name: 'ProductUnitConversionDelete', value: 'productUnitConversionDelete' },
    { name: 'ProductUnitConversionRead', value: 'productUnitConversionRead' },
    { name: 'ProductUnitConversionReadById', value: 'productUnitConversionReadById' },
    { name: 'ProductUnitConversionUpdate', value: 'productUnitConversionUpdate' },
    { name: 'ProductUpdate', value: 'productUpdate' },
    { name: 'ProductVariantCreate', value: 'productVariantCreate' },
    { name: 'ProductVariantDelete', value: 'productVariantDelete' },
    { name: 'ProductVariantRead', value: 'productVariantRead' },
    { name: 'ProductVariantReadById', value: 'productVariantReadById' },
    { name: 'ProductVariantUpdate', value: 'productVariantUpdate' },
    { name: 'UnitCreate', value: 'unitCreate' },
    { name: 'UnitDelete', value: 'unitDelete' },
    { name: 'UnitRead', value: 'unitRead' },
    { name: 'UnitReadById', value: 'unitReadById' },
    { name: 'UnitUpdate', value: 'unitUpdate' }
  ],
  default: 'codeConversionCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
