import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'AccountCategoryCreate', value: 'accountCategoryCreate' },
    { name: 'AccountCategoryDelete', value: 'accountCategoryDelete' },
    { name: 'AccountCategoryRead', value: 'accountCategoryRead' },
    { name: 'AccountCategoryReadById', value: 'accountCategoryReadById' },
    { name: 'AccountCategoryUpdate', value: 'accountCategoryUpdate' },
    { name: 'AccountChartCreate', value: 'accountChartCreate' },
    { name: 'AccountChartDelete', value: 'accountChartDelete' },
    { name: 'AccountChartOpClone', value: 'accountChartOpClone' },
    { name: 'AccountChartOpImport', value: 'accountChartOpImport' },
    { name: 'AccountChartOpLevelCreate', value: 'accountChartOpLevelCreate' },
    { name: 'AccountChartOpLevelDelete', value: 'accountChartOpLevelDelete' },
    { name: 'AccountChartOpLevelUpdate', value: 'accountChartOpLevelUpdate' },
    { name: 'AccountChartOpNextShortCode', value: 'accountChartOpNextShortCode' },
    { name: 'AccountChartRead', value: 'accountChartRead' },
    { name: 'AccountChartReadById', value: 'accountChartReadById' },
    { name: 'AccountChartUpdate', value: 'accountChartUpdate' },
    { name: 'AccountConversionChartCreate', value: 'accountConversionChartCreate' },
    { name: 'AccountConversionChartDelete', value: 'accountConversionChartDelete' },
    { name: 'AccountConversionChartRead', value: 'accountConversionChartRead' },
    { name: 'AccountConversionChartReadById', value: 'accountConversionChartReadById' },
    { name: 'AccountConversionChartUpdate', value: 'accountConversionChartUpdate' },
    { name: 'AccountConversionCreate', value: 'accountConversionCreate' },
    { name: 'AccountConversionDelete', value: 'accountConversionDelete' },
    { name: 'AccountConversionRead', value: 'accountConversionRead' },
    { name: 'AccountConversionReadById', value: 'accountConversionReadById' },
    { name: 'AccountConversionUpdate', value: 'accountConversionUpdate' },
    { name: 'AccountCreate', value: 'accountCreate' },
    { name: 'AccountDefaultCreate', value: 'accountDefaultCreate' },
    { name: 'AccountDefaultDelete', value: 'accountDefaultDelete' },
    { name: 'AccountDefaultOpRead', value: 'accountDefaultOpRead' },
    { name: 'AccountDefaultRead', value: 'accountDefaultRead' },
    { name: 'AccountDefaultReadById', value: 'accountDefaultReadById' },
    { name: 'AccountDefaultUpdate', value: 'accountDefaultUpdate' },
    { name: 'AccountDelete', value: 'accountDelete' },
    { name: 'AccountFiscalYearRead', value: 'accountFiscalYearRead' },
    { name: 'AccountRead', value: 'accountRead' },
    { name: 'AccountReadById', value: 'accountReadById' },
    { name: 'AccountUpdate', value: 'accountUpdate' },
    { name: 'AssetInventoryCurrentRead', value: 'assetInventoryCurrentRead' },
    { name: 'AssetInventoryRead', value: 'assetInventoryRead' },
    { name: 'AssetTagRead', value: 'assetTagRead' },
    { name: 'AssetTagReadById', value: 'assetTagReadById' },
    { name: 'FiscalYearOpClose', value: 'fiscalYearOpClose' },
    { name: 'JournalEntryCreate', value: 'journalEntryCreate' },
    { name: 'JournalEntryDelete', value: 'journalEntryDelete' },
    { name: 'JournalEntryOpCreate', value: 'journalEntryOpCreate' },
    { name: 'JournalEntryOpPublish', value: 'journalEntryOpPublish' },
    { name: 'JournalEntryOpPublishRevert', value: 'journalEntryOpPublishRevert' },
    { name: 'JournalEntryOpUpdate', value: 'journalEntryOpUpdate' },
    { name: 'JournalEntryRead', value: 'journalEntryRead' },
    { name: 'JournalEntryReadById', value: 'journalEntryReadById' },
    { name: 'JournalEntryUpdate', value: 'journalEntryUpdate' },
    { name: 'JournalItemCreate', value: 'journalItemCreate' },
    { name: 'JournalItemDelete', value: 'journalItemDelete' },
    { name: 'JournalItemRead', value: 'journalItemRead' },
    { name: 'JournalItemReadById', value: 'journalItemReadById' },
    { name: 'JournalItemUpdate', value: 'journalItemUpdate' },
    { name: 'LedgerItemBalanceRead', value: 'ledgerItemBalanceRead' },
    { name: 'LedgerItemRead', value: 'ledgerItemRead' },
    { name: 'LedgerItemReadById', value: 'ledgerItemReadById' },
    { name: 'ResultCenterChartCreate', value: 'resultCenterChartCreate' },
    { name: 'ResultCenterChartDelete', value: 'resultCenterChartDelete' },
    { name: 'ResultCenterChartOpLevelCreate', value: 'resultCenterChartOpLevelCreate' },
    { name: 'ResultCenterChartOpLevelDelete', value: 'resultCenterChartOpLevelDelete' },
    { name: 'ResultCenterChartOpLevelUpdate', value: 'resultCenterChartOpLevelUpdate' },
    { name: 'ResultCenterChartRead', value: 'resultCenterChartRead' },
    { name: 'ResultCenterChartReadById', value: 'resultCenterChartReadById' },
    { name: 'ResultCenterChartUpdate', value: 'resultCenterChartUpdate' },
    { name: 'ResultCenterCreate', value: 'resultCenterCreate' },
    { name: 'ResultCenterDelete', value: 'resultCenterDelete' },
    { name: 'ResultCenterRead', value: 'resultCenterRead' },
    { name: 'ResultCenterReadById', value: 'resultCenterReadById' },
    { name: 'ResultCenterUpdate', value: 'resultCenterUpdate' }
  ],
  default: 'accountCategoryCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
