import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'AccessPointCreate', value: 'accessPointCreate' },
    { name: 'AccessPointDelete', value: 'accessPointDelete' },
    { name: 'AccessPointOpValidate', value: 'accessPointOpValidate' },
    { name: 'AccessPointRead', value: 'accessPointRead' },
    { name: 'AccessPointReadById', value: 'accessPointReadById' },
    { name: 'AccessPointUpdate', value: 'accessPointUpdate' },
    { name: 'AccessProfileCreate', value: 'accessProfileCreate' },
    { name: 'AccessProfileDelete', value: 'accessProfileDelete' },
    { name: 'AccessProfileRead', value: 'accessProfileRead' },
    { name: 'AccessProfileReadById', value: 'accessProfileReadById' },
    { name: 'AccessProfileUpdate', value: 'accessProfileUpdate' },
    { name: 'GrantCreate', value: 'grantCreate' },
    { name: 'GrantDelete', value: 'grantDelete' },
    { name: 'GrantRead', value: 'grantRead' },
    { name: 'GrantReadById', value: 'grantReadById' },
    { name: 'GroupCreate', value: 'groupCreate' },
    { name: 'GroupDelete', value: 'groupDelete' },
    { name: 'GroupOpClone', value: 'groupOpClone' },
    { name: 'GroupRead', value: 'groupRead' },
    { name: 'GroupReadById', value: 'groupReadById' },
    { name: 'GroupUpdate', value: 'groupUpdate' },
    { name: 'KeyStoreCreate', value: 'keyStoreCreate' },
    { name: 'KeyStoreDelete', value: 'keyStoreDelete' },
    { name: 'KeyStoreOpReadContent', value: 'keyStoreOpReadContent' },
    { name: 'KeyStoreRead', value: 'keyStoreRead' },
    { name: 'KeyStoreReadById', value: 'keyStoreReadById' },
    { name: 'KeyStoreUpdate', value: 'keyStoreUpdate' },
    { name: 'RoleAccessPointCreate', value: 'roleAccessPointCreate' },
    { name: 'RoleAccessPointDelete', value: 'roleAccessPointDelete' },
    { name: 'RoleAccessPointRead', value: 'roleAccessPointRead' },
    { name: 'RoleAccessPointReadById', value: 'roleAccessPointReadById' },
    { name: 'RoleRead', value: 'roleRead' },
    { name: 'RoleReadById', value: 'roleReadById' },
    { name: 'SessionContext', value: 'sessionContext' },
    { name: 'SessionDelete', value: 'sessionDelete' },
    { name: 'SessionOpGetCurrent', value: 'sessionOpGetCurrent' },
    { name: 'SessionRead', value: 'sessionRead' },
    { name: 'SessionReadById', value: 'sessionReadById' },
    { name: 'TokenOpInvalidate', value: 'tokenOpInvalidate' },
    { name: 'TokenOpInvalidateCurrent', value: 'tokenOpInvalidateCurrent' },
    { name: 'TokenOpRenew', value: 'tokenOpRenew' },
    { name: 'TokenOpRequest', value: 'tokenOpRequest' },
    { name: 'TokenOpRequestPermanent', value: 'tokenOpRequestPermanent' },
    { name: 'UserCreate', value: 'userCreate' },
    { name: 'UserDelete', value: 'userDelete' },
    { name: 'UserOpActivate', value: 'userOpActivate' },
    { name: 'UserOpAuthenticate', value: 'userOpAuthenticate' },
    { name: 'UserOpChangeEmail', value: 'userOpChangeEmail' },
    { name: 'UserOpChangeEmailConfirmation', value: 'userOpChangeEmailConfirmation' },
    { name: 'UserOpChangePassword', value: 'userOpChangePassword' },
    { name: 'UserOpChangePasswordThird', value: 'userOpChangePasswordThird' },
    { name: 'UserOpCreate', value: 'userOpCreate' },
    { name: 'UserOpCreateConfirmation', value: 'userOpCreateConfirmation' },
    { name: 'UserOpCreateResend', value: 'userOpCreateResend' },
    { name: 'UserOpGrantOptionAdd', value: 'userOpGrantOptionAdd' },
    { name: 'UserOpGrantOptionRemove', value: 'userOpGrantOptionRemove' },
    { name: 'UserOpInactivate', value: 'userOpInactivate' },
    { name: 'UserOpResetPassword', value: 'userOpResetPassword' },
    { name: 'UserOpResetPasswordConfirmation', value: 'userOpResetPasswordConfirmation' },
    { name: 'UserOpUnlock', value: 'userOpUnlock' },
    { name: 'UserOpUpdate', value: 'userOpUpdate' },
    { name: 'UserPermissionRead', value: 'userPermissionRead' },
    { name: 'UserRead', value: 'userRead' },
    { name: 'UserReadById', value: 'userReadById' },
    { name: 'UserUpdate', value: 'userUpdate' }
  ],
  default: 'accessPointCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
