import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'DfeNfeProcInCreate', value: 'dfeNfeProcInCreate' },
    { name: 'DfeNfeProcInDelete', value: 'dfeNfeProcInDelete' },
    { name: 'DfeNfeProcInOpIncomingInvoiceCreate', value: 'dfeNfeProcInOpIncomingInvoiceCreate' },
    { name: 'DfeNfeProcInOpIncomingInvoiceCreateRevert', value: 'dfeNfeProcInOpIncomingInvoiceCreateRevert' },
    { name: 'DfeNfeProcInRead', value: 'dfeNfeProcInRead' },
    { name: 'DfeNfeProcInReadById', value: 'dfeNfeProcInReadById' },
    { name: 'DfeNfeProcOutDelete', value: 'dfeNfeProcOutDelete' },
    { name: 'DfeNfeProcOutOpCancel', value: 'dfeNfeProcOutOpCancel' },
    { name: 'DfeNfeProcOutOpConfirm', value: 'dfeNfeProcOutOpConfirm' },
    { name: 'DfeNfeProcOutOpCorrect', value: 'dfeNfeProcOutOpCorrect' },
    { name: 'DfeNfeProcOutOpCreate', value: 'dfeNfeProcOutOpCreate' },
    { name: 'DfeNfeProcOutOpDownload', value: 'dfeNfeProcOutOpDownload' },
    { name: 'DfeNfeProcOutOpOutgoingInvoiceCreate', value: 'dfeNfeProcOutOpOutgoingInvoiceCreate' },
    { name: 'DfeNfeProcOutOpSign', value: 'dfeNfeProcOutOpSign' },
    { name: 'DfeNfeProcOutOpSignRevert', value: 'dfeNfeProcOutOpSignRevert' },
    { name: 'DfeNfeProcOutOpTransmit', value: 'dfeNfeProcOutOpTransmit' },
    { name: 'DfeNfeProcOutOpUpload', value: 'dfeNfeProcOutOpUpload' },
    { name: 'DfeNfeProcOutRead', value: 'dfeNfeProcOutRead' },
    { name: 'DfeNfeProcOutReadById', value: 'dfeNfeProcOutReadById' },
    { name: 'DfeOpReadContent', value: 'dfeOpReadContent' },
    { name: 'DfeProcEventoNFeInRead', value: 'dfeProcEventoNFeInRead' },
    { name: 'DfeProcEventoNFeInReadById', value: 'dfeProcEventoNFeInReadById' },
    { name: 'DfeProcEventoNFeOutRead', value: 'dfeProcEventoNFeOutRead' },
    { name: 'DfeProcEventoNFeOutReadById', value: 'dfeProcEventoNFeOutReadById' },
    { name: 'DfeProcInutNFeCreate', value: 'dfeProcInutNFeCreate' },
    { name: 'DfeProcInutNFeRead', value: 'dfeProcInutNFeRead' },
    { name: 'DfeProcInutNFeReadById', value: 'dfeProcInutNFeReadById' },
    { name: 'DfeRead', value: 'dfeRead' },
    { name: 'DfeReadById', value: 'dfeReadById' },
    { name: 'DfeResEventoRead', value: 'dfeResEventoRead' },
    { name: 'DfeResEventoReadById', value: 'dfeResEventoReadById' },
    { name: 'DfeResNFeInOpManifest', value: 'dfeResNFeInOpManifest' },
    { name: 'DfeResNFeInRead', value: 'dfeResNFeInRead' },
    { name: 'DfeResNFeInReadById', value: 'dfeResNFeInReadById' },
    { name: 'DocumentSefazOpFetch', value: 'documentSefazOpFetch' },
    { name: 'SpedOpExport', value: 'spedOpExport' }
  ],
  default: 'dfeNfeProcInCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
