import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'PersonAddressCreate', value: 'personAddressCreate' },
    { name: 'PersonAddressDelete', value: 'personAddressDelete' },
    { name: 'PersonAddressOpSetDefault', value: 'personAddressOpSetDefault' },
    { name: 'PersonAddressRead', value: 'personAddressRead' },
    { name: 'PersonAddressReadById', value: 'personAddressReadById' },
    { name: 'PersonAddressUpdate', value: 'personAddressUpdate' },
    { name: 'PersonCommentCreate', value: 'personCommentCreate' },
    { name: 'PersonCommentDelete', value: 'personCommentDelete' },
    { name: 'PersonCommentRead', value: 'personCommentRead' },
    { name: 'PersonCommentReadById', value: 'personCommentReadById' },
    { name: 'PersonCommentUpdate', value: 'personCommentUpdate' },
    { name: 'PersonCompactRead', value: 'personCompactRead' },
    { name: 'PersonCompactReadById', value: 'personCompactReadById' },
    { name: 'PersonContactCreate', value: 'personContactCreate' },
    { name: 'PersonContactDelete', value: 'personContactDelete' },
    { name: 'PersonContactRead', value: 'personContactRead' },
    { name: 'PersonContactReadById', value: 'personContactReadById' },
    { name: 'PersonContactUpdate', value: 'personContactUpdate' },
    { name: 'PersonCreate', value: 'personCreate' },
    { name: 'PersonDelete', value: 'personDelete' },
    { name: 'PersonDocumentCreate', value: 'personDocumentCreate' },
    { name: 'PersonDocumentDelete', value: 'personDocumentDelete' },
    { name: 'PersonDocumentRead', value: 'personDocumentRead' },
    { name: 'PersonDocumentReadById', value: 'personDocumentReadById' },
    { name: 'PersonDocumentUpdate', value: 'personDocumentUpdate' },
    { name: 'PersonGroupCreate', value: 'personGroupCreate' },
    { name: 'PersonGroupDelete', value: 'personGroupDelete' },
    { name: 'PersonGroupRead', value: 'personGroupRead' },
    { name: 'PersonGroupReadById', value: 'personGroupReadById' },
    { name: 'PersonGroupUpdate', value: 'personGroupUpdate' },
    { name: 'PersonOpReadFromPersonDirectory', value: 'personOpReadFromPersonDirectory' },
    { name: 'PersonRead', value: 'personRead' },
    { name: 'PersonReadById', value: 'personReadById' },
    { name: 'PersonUpdate', value: 'personUpdate' }
  ],
  default: 'personAddressCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
