import type { INodeProperties } from 'n8n-workflow';

export const operations: INodeProperties[] = [{
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  options: [
    { name: 'CurrencyCreate', value: 'currencyCreate' },
    { name: 'CurrencyDelete', value: 'currencyDelete' },
    { name: 'CurrencyExchangeRateCreate', value: 'currencyExchangeRateCreate' },
    { name: 'CurrencyExchangeRateDelete', value: 'currencyExchangeRateDelete' },
    { name: 'CurrencyExchangeRateOpConvert', value: 'currencyExchangeRateOpConvert' },
    { name: 'CurrencyExchangeRateOpGetExchangeRate', value: 'currencyExchangeRateOpGetExchangeRate' },
    { name: 'CurrencyExchangeRateRead', value: 'currencyExchangeRateRead' },
    { name: 'CurrencyExchangeRateReadById', value: 'currencyExchangeRateReadById' },
    { name: 'CurrencyExchangeRateUpdate', value: 'currencyExchangeRateUpdate' },
    { name: 'CurrencyOpReadByCode', value: 'currencyOpReadByCode' },
    { name: 'CurrencyRead', value: 'currencyRead' },
    { name: 'CurrencyReadById', value: 'currencyReadById' },
    { name: 'CurrencyUpdate', value: 'currencyUpdate' },
    { name: 'PayableCreate', value: 'payableCreate' },
    { name: 'PayableDelete', value: 'payableDelete' },
    { name: 'PayableOpApprove', value: 'payableOpApprove' },
    { name: 'PayableOpApproveRevert', value: 'payableOpApproveRevert' },
    { name: 'PayableOpChangeWallet', value: 'payableOpChangeWallet' },
    { name: 'PayableOpPrepare', value: 'payableOpPrepare' },
    { name: 'PayableOpPrepareRevert', value: 'payableOpPrepareRevert' },
    { name: 'PayableOpRepeat', value: 'payableOpRepeat' },
    { name: 'PayableOpSettle', value: 'payableOpSettle' },
    { name: 'PayableOpUpdate', value: 'payableOpUpdate' },
    { name: 'PayableOpUpdatePrepared', value: 'payableOpUpdatePrepared' },
    { name: 'PayableRead', value: 'payableRead' },
    { name: 'PayableReadById', value: 'payableReadById' },
    { name: 'PayableSettlementBillingTitleRead', value: 'payableSettlementBillingTitleRead' },
    { name: 'PayableSettlementBillingTitleReadById', value: 'payableSettlementBillingTitleReadById' },
    { name: 'PayableSettlementDelete', value: 'payableSettlementDelete' },
    { name: 'PayableSettlementMethodRead', value: 'payableSettlementMethodRead' },
    { name: 'PayableSettlementMethodReadById', value: 'payableSettlementMethodReadById' },
    { name: 'PayableSettlementRead', value: 'payableSettlementRead' },
    { name: 'PayableSettlementReadById', value: 'payableSettlementReadById' },
    { name: 'PayableUpdate', value: 'payableUpdate' },
    { name: 'ReceivableCreate', value: 'receivableCreate' },
    { name: 'ReceivableDelete', value: 'receivableDelete' },
    { name: 'ReceivableOpApprove', value: 'receivableOpApprove' },
    { name: 'ReceivableOpApproveRevert', value: 'receivableOpApproveRevert' },
    { name: 'ReceivableOpPrepare', value: 'receivableOpPrepare' },
    { name: 'ReceivableOpPrepareRevert', value: 'receivableOpPrepareRevert' },
    { name: 'ReceivableOpRepeat', value: 'receivableOpRepeat' },
    { name: 'ReceivableOpSend', value: 'receivableOpSend' },
    { name: 'ReceivableOpSettle', value: 'receivableOpSettle' },
    { name: 'ReceivableOpUpdate', value: 'receivableOpUpdate' },
    { name: 'ReceivableOpUpdatePrepared', value: 'receivableOpUpdatePrepared' },
    { name: 'ReceivableRead', value: 'receivableRead' },
    { name: 'ReceivableReadById', value: 'receivableReadById' },
    { name: 'ReceivableSettlementBillingTitleRead', value: 'receivableSettlementBillingTitleRead' },
    { name: 'ReceivableSettlementBillingTitleReadById', value: 'receivableSettlementBillingTitleReadById' },
    { name: 'ReceivableSettlementDelete', value: 'receivableSettlementDelete' },
    { name: 'ReceivableSettlementMethodRead', value: 'receivableSettlementMethodRead' },
    { name: 'ReceivableSettlementMethodReadById', value: 'receivableSettlementMethodReadById' },
    { name: 'ReceivableSettlementRead', value: 'receivableSettlementRead' },
    { name: 'ReceivableSettlementReadById', value: 'receivableSettlementReadById' },
    { name: 'ReceivableUpdate', value: 'receivableUpdate' }
  ],
  default: 'currencyCreate',
}];

export const fields: INodeProperties[] = [
  {
    displayName: 'ID',
    name: 'id',
    type: 'number',
    default: null,
  },
  {
    displayName: 'Body',
    name: 'body',
    type: 'json',
    default: {},
  },
];
